SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE  `book_author`;
TRUNCATE TABLE  `book_genre`;
TRUNCATE TABLE  `book`;
TRUNCATE TABLE  `author`;
TRUNCATE TABLE  `genre`;
SET FOREIGN_KEY_CHECKS=1;
INSERT INTO `genre`(`name`) VALUES('Fantasy');
INSERT INTO `genre`(`name`) VALUES('Adventure');
INSERT INTO `genre`(`name`) VALUES('Romance');
INSERT INTO `genre`(`name`) VALUES('Mystery');
INSERT INTO `genre`(`name`) VALUES('Horror');
INSERT INTO `author`(`name`, `surname`) VALUES('William', 'Shakespeare');
INSERT INTO `author`(`name`, `surname`) VALUES('Agatha', 'Christie');
INSERT INTO `author`(`name`, `surname`) VALUES('Barbara', 'Cartland');
INSERT INTO `author`(`name`, `surname`) VALUES('Danielle', 'Steel');
INSERT INTO `author`(`name`, `surname`) VALUES('Harold', 'Robbins');
INSERT INTO `book`(`name`, `isbn`, `date`) VALUES('Watchmen', '453-56-18', '2011-01-12');
INSERT INTO `book`(`name`, `isbn`, `date`) VALUES('The Walking Dead: Compendium One', '354-76-78', '1996-03-05');
INSERT INTO `book`(`name`, `isbn`, `date`) VALUES('The Boy, the Mole, the Fox and the Horse', '23-54-123', '1857-08-11');
INSERT INTO `book`(`name`, `isbn`, `date`) VALUES('The Night Fire', '8976-12-3', '1997-02-07');
INSERT INTO `book`(`name`, `isbn`, `date`) VALUES('And Then There Were None', '321-654-78', '1954-09-09');
INSERT INTO `book_genre`(`bookId`, `genreId`) VALUES(1, 1);
INSERT INTO `book_genre`(`bookId`, `genreId`) VALUES(1, 2);
INSERT INTO `book_genre`(`bookId`, `genreId`) VALUES(2, 2);
INSERT INTO `book_genre`(`bookId`, `genreId`) VALUES(3, 3);
INSERT INTO `book_genre`(`bookId`, `genreId`) VALUES(4, 4);
INSERT INTO `book_genre`(`bookId`, `genreId`) VALUES(4, 1);
INSERT INTO `book_genre`(`bookId`, `genreId`) VALUES(4, 2);
INSERT INTO `book_genre`(`bookId`, `genreId`) VALUES(5, 5);
INSERT INTO `book_author`(`bookId`, `authorId`) VALUES(1, 1);
INSERT INTO `book_author`(`bookId`, `authorId`) VALUES(1, 2);
INSERT INTO `book_author`(`bookId`, `authorId`) VALUES(1, 3);
INSERT INTO `book_author`(`bookId`, `authorId`) VALUES(2, 2);
INSERT INTO `book_author`(`bookId`, `authorId`) VALUES(3, 3);
INSERT INTO `book_author`(`bookId`, `authorId`) VALUES(3, 1);
INSERT INTO `book_author`(`bookId`, `authorId`) VALUES(4, 4);
INSERT INTO `book_author`(`bookId`, `authorId`) VALUES(5, 5);
INSERT INTO `book_author`(`bookId`, `authorId`) VALUES(5, 2);